<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root-element [
    <!ELEMENT root-element (school)>
    <!ELEMENT school (student+)>
    <!ELEMENT student (name, email)>
    <!ELEMENT  name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
     
    <!ATTLIST student id  CDATA #IMPLIED>
]>
<root-element>

    
<school>
    <student id="1">
        <name>moiz</name>
        <email>moiz@gmail.com</email>
    </student>

    <student id="2">
        <name>ali</name>
        <email>ali@gmail.com</email>
    </student>
</school>
</root-element>
